<?php
require_once("fpdf/fpdf.php");
require_once("User.php");
if(!isset($po_id) && !isset($id_supp)){
	$po_id =$_GET["po_id"];
	$id_supp =$_GET["id_supp"];
} else{
	$po_id = $id_comp;
	$id_supp = $supp;
}
$sql_supp = "SELECT * FROM suppliers where idsuppliers = {$id_supp}";
$res_supp = exec_query($sql_supp);
while($row = mysqli_fetch_assoc($res_supp)){
	$name = $row["name"];
	$address = $row["address"];
	$telephone = $row["telephone"];
	$contact = $row["contact"];
	$email = $row["email"];
}
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', 'B', 14);
$pdf->Image("../public/images/logo.png", 10,8,36,17, 'PNG');
$pdf->Ln(22);
$pdf->Cell(45,8, 'Proforma Invoice');
$pdf->Ln(8);
$pdf->SetFont('Arial','',7);
$pdf->Cell(110,7, 'INVOICED TO: ');
$pdf->Cell(8,7, 'INVOICED TO: ');
$pdf->Ln(3);
$pdf->Cell(110,7, 'COMPANY NAME: SERVICE TRADING S.A. DE C.V.');
$pdf->Cell(20,7, 'COMPANY NAME:'. $name);
$pdf->Ln(3);
$pdf->Cell(110,7, 'MARIO PANI #200 DELEGACION CUAJIMALPA MORELOS');
$pdf->Cell(20,7, 'ADDRESS: '. $address);
$pdf->Ln(3);
$pdf->Cell(110,7, 'MEXICO D.E., C.PO5348 MEXICO TAX ID: STR921014ARO');
$pdf->Cell(20,7, 'VENDOR CODE: '. $id_supp);
$pdf->Ln(3);
$pdf->Cell(110,7, 'CUSTOMER NO. TCU.MX.001');
$pdf->Cell(110,7, 'CONTACT PERSON: ' . $contact);
$pdf->Ln(3);
$pdf->Cell(110,7, 'COUNTRY: MEXICO');
$pdf->Cell(20,7, 'Email: '. $email);
$pdf->Ln(3);
$pdf->Cell(110,7, 'CONTACT PERSON: Isabella');
$pdf->Cell(20,7, 'Cellphone: '. $telephone);
$pdf->Ln(3);
$pdf->Cell(20,7, 'COUNTRY: MEXICO');
$pdf->Ln(5);
$pdf->Cell(20,3, 'EMAIL: izhang@liverpool.com');
$sql_comp = "SELECT * FROM comp_ent WHERE id =" .$po_id;
$res_comp = exec_query($sql_comp);
while($row = mysqli_fetch_assoc($res_comp)){
	$id_supp = $row["id_supp"];
	$person_name = $row["person_name"];
	$remarks = $row["remarks"];
	$tot = $row["tot_gen"];
	$date = $row["created_date"];
}
$pdf->Ln(5);
$pdf->SetFont('Arial','',9);
$pdf->Cell(110,10,"Responsable: " . ucfirst($person_name));
$pdf->Cell(15,10,"Date Issued: " . $date);
$pdf->Ln(6);
$pdf->Cell(20,5,"Order #".$po_id);
$pdf->Ln(12);
$pdf->Cell(9,10,"");
$pdf->SetFont('Arial','B',11);
$pdf->Cell(40,10,"Photo");
$pdf->Cell(30,10,'Style');
$pdf->Cell(25,10,'Composition');
$pdf->Cell(20,10,'Color');
$pdf->Cell(20,10,'MOQ');
$pdf->Cell(10,10,'FOB');
$pdf->Ln(13);
$sql =  "SELECT * FROM pi_entries WHERE id_comp_ent = ". $po_id;
$pdf->Cell(10,10,"");
$res_set = exec_query($sql);
$pdf->SetFont('Arial','',10);
$y_img = 99;
while($row = mysqli_fetch_assoc($res_set)){
	$pdf->Image("../../uploads/".$row["photo_path"]."",20,$y_img,20,20);
	$fob = sprintf('%01.2f', $row["fob_sh"]);
	$pdf->Cell(40,20,"");
	$pdf->Cell(30,7, $row["style"]);
	$pdf->Cell(25,7, $row["composition"]);
	$pdf->Cell(20,7, $row["color"]);
	$pdf->Cell(20,7, $row["moq"]);
	$pdf->Cell(10,7, $fob . " USD");
	$pdf->Ln(22);
	$pdf->Cell(10,10,"");
	$y_img = $y_img +22;
}
$pdf->SetFont('Arial','B',11);
$pdf->Cell(110,20,"");
$pdf->Cell(20,10,"Grand Total: $".$tot."USD");
$pdf->Ln(5);
$pdf->Cell(10,10,"Remarks:");
$pdf->Ln(4);
$pdf->SetFont('Arial','',11);
$pdf->Cell(30,20, $remarks);
$pdf->Ln(20);
$pdf->SetFont('Arial','',10);
$sql_pays = "SELECT * FROM pays where id_suppliers = {$id_supp}";
$res_pays = exec_query($sql_pays);
while($row = mysqli_fetch_assoc($res_pays)){
	$pdf->Cell(40,7, "Payment conditions: ");
	$pdf->Cell(65,7,ucfirst($row["pay_cond"]));
	$pdf->Cell(40,7,"Expiration conditions:");
	$pdf->Cell(20,7, ucfirst($row["expiration_conditions"]));
	$pdf->Ln(5);
	$pdf->Cell(40,7,"Expiration days:");
	$pdf->Cell(65,7, $row["exp_days"]);
	$pdf->Cell(20,7,"Currency:");
	$pdf->Cell(15,7,strtoupper($row["currency"]));
	$pdf->Ln(5);
	$pdf->SetFont('Arial','',10);
	$pdf->Cell(20,7,"Beneficiary: ");
	$pdf->Cell(85,7, ucfirst($row["beneficiary"]));
	$pdf->Cell(10,7,"City:");
	$pdf->Cell(30,7, ucfirst($row["bank_city"]));
	$pdf->Ln(5);
	$pdf->Cell(35,7,"Correspondant bank: ");
	$pdf->Cell(70,7, ucfirst($row["bank_name"]));
	$pdf->Cell(15,7,"Country: ");
	$pdf->Cell(30,7, ucfirst($row["bank_country"]));
	$pdf->Ln(8);
	$pdf->Cell(25,7,"Bank account:",1);
	$pdf->Cell(80,7, $row["bank_account"],1);
	$pdf->Cell(20,7,"Branch:",1);
	$pdf->Cell(40,7, $row["branch"],1);
	$pdf->Ln(6);
	$pdf->Cell(25,7,"Bank code:",1);
	$pdf->Cell(80,7, $row["bank_code"],1);
	$pdf->Cell(20,7,"Bank key:",1);
	$pdf->Cell(40,7, $row["bank_key"],1);
	$pdf->Ln(6);
	$pdf->Cell(25,7,"Swift:",1);
	$pdf->Cell(80,7, $row["swift"],1);
	$pdf->Cell(20,7,"Clabe:",1);
	$pdf->Cell(40,7, $row["clabe"],1);
}
?>
