<?php
require_once("fpdf/fpdf.php");
require_once("User.php");
	$id_supp =$_GET["id_supp"];
	$sql_supp = "SELECT * FROM suppliers where idsuppliers = {$id_supp}";
	$res_supp = exec_query($sql_supp);
	$sql_pays = "SELECT * FROM pays where id_suppliers = {$id_supp}";
	$res_pays = exec_query($sql_pays);
	$pdf = new FPDF();
	$pdf->AddPage();
	$pdf->SetFont('Arial', '', 12);
	$pdf->Image("../public/images/livlog.png", 10,8,55,17, 'PNG');
	$pdf->Ln(15);
	while($row = mysqli_fetch_assoc($res_supp)){
		$pdf->Cell(120,7,"");
		$pdf->Cell(15,7,"Date:");
		$pdf->Cell(20,7,$row["svn_fs_node_created_rev(fsroot, path)date"]);
		$pdf->Ln(8);
	$pdf->SetFont('Arial', 'B', 12);
	$pdf->Cell(180,9,"FOREIGN SUPPLIER / IMPORT SERVICE PROVIDER- ADDITION OR UPDATE REQUEST");
	$pdf->Ln(10);
	$pdf->Cell(100,7,"A. Foreign Supplier / Import Service Provider - General Information");
	$pdf->Ln(8);
	$pdf->SetFont('Arial', '', 10);
		$pdf->Cell(25,7,"Supplier code: ");
		$pdf->Cell(80,7, $row["idsuppliers"]);
		$pdf->Cell(15,7,"Society: ");
		$pdf->Cell(15,7, $row["society"]);
		$pdf->Ln(8);
		$pdf->Cell(25,7, "Supplier name: ");
		$pdf->Cell(80,7,ucfirst($row["name"]));
		$pdf->Cell(25,7,"Organization:");
		$pdf->Cell(15,7,$row["organization"]);
		$pdf->Ln(8);
		$pdf->Cell(30,7,"Supplier address: ");
		$pdf->Cell(100,7,$row["address"]);
		$pdf->Ln(8);
		$pdf->Cell(15,7,"Fiscal ID:");
		$pdf->Cell(90,7,$row["fiscal_id"]);
		$pdf->Cell(10,7, "ZP: ");
		$pdf->Cell(15,7,$row["zp"]);
		$pdf->Ln(8);
		$pdf->Cell(20,7, "Telephone: ");
		$pdf->Cell(40,7,$row["telephone"]);
		$pdf->Cell(10,7, "Ext.: ");
		$pdf->Cell(35,7,$row["ext"]);
		$pdf->Cell(10, 7, "Fax:");
		$pdf->Cell(20,7,$row["fax"]);
		$pdf->Ln(8);
		$pdf->Cell(15,7, "Contact: ");
		$pdf->Cell(90,7,ucfirst($row["contact"]));
		$pdf->Cell(13,7, "Email: ");
		$pdf->Cell(45,7,$row["email"]);
	}
	$pdf->Ln(8);
	$pdf->SetFont('Arial','B',12);
	$pdf->Cell(50,7,"B. Conditions");
	$pdf->Ln(8);
	$pdf->SetFont('Arial','',10);
	while($row = mysqli_fetch_assoc($res_pays)){	
		$pdf->Cell(40,7, "Payment conditions: ");
		$pdf->Cell(65,7,ucfirst($row["pay_cond"]));
		$pdf->Cell(40,7,"Expiration conditions:");
		$pdf->Cell(20,7, ucfirst($row["expiration_conditions"]));
		$pdf->Ln(8);
		$pdf->Cell(40,7,"Expiration days:");
		$pdf->Cell(65,7, $row["exp_days"]);
		$pdf->Cell(20,7,"Currency:");
		$pdf->Cell(15,7,strtoupper($row["currency"]));
		$pdf->Ln(8);
		$pdf->SetFont('Arial','B',12);
		$pdf->Cell(30,7,"C. Bank information");
		$pdf->Ln(8);
		$pdf->SetFont('Arial','',10);
		$pdf->Cell(20,7,"Beneficiary: ");
		$pdf->Cell(30,7, ucfirst($row["beneficiary"]));
		$pdf->Ln(8);
		$pdf->Cell(35,7,"Correspondant bank: ");
		$pdf->Cell(50,7, ucfirst($row["bank_name"]));
		$pdf->Ln(8);
		$pdf->Cell(15,7,"Country: ");
		$pdf->Cell(90,7, ucfirst($row["bank_country"]));
		$pdf->Cell(10,7,"City: ");
		$pdf->Cell(30,7, ucfirst($row["bank_city"]));
		$pdf->Ln(8);
		$pdf->Cell(25,7,"Bank account:",1);
		$pdf->Cell(80,7, $row["bank_account"],1);
		$pdf->Cell(20,7,"Branch:",1);
		$pdf->Cell(40,7, $row["branch"],1);
		$pdf->Ln(8);
		$pdf->Cell(25,7,"Bank code:",1);
		$pdf->Cell(80,7, $row["bank_code"],1);
		$pdf->Cell(20,7,"Bank key:",1);
		$pdf->Cell(40,7, $row["bank_key"],1);
		$pdf->Ln(8);
		$pdf->Cell(25,7,"Aba:",1);
		$pdf->Cell(80,7, $row["aba"],1);
		$pdf->Cell(20,7,"Iban:",1);
		$pdf->Cell(40,7, $row["iban"],1);
		$pdf->Ln(8);
		$pdf->Cell(25,7,"Swift:",1);
		$pdf->Cell(80,7, $row["swift"],1);
		$pdf->Cell(20,7,"Clabe:",1);
		$pdf->Cell(40,7, $row["clabe"],1);
	}
	$pdf->Ln(13);
	$pdf->Cell(45,7,"Director Commercial Area",1);
	$pdf->Cell(30,7,"");
	$pdf->Cell(45,7,"Treasury, Foreign Currency",1);
	$pdf->Cell(30,7,"");
	$pdf->Cell(45,7,"Import Comptrollership",1);
	$pdf->Ln(7);
	$pdf->Cell(45,45,"",1);
	$pdf->Cell(30,7,"");
	$pdf->Cell(45,45,"",1);
	$pdf->Cell(30,7,"");
	$pdf->Cell(45,45,"",1);
	$pdf->Ln(40);
	$pdf->SetFont('Arial','i',8);
	$pdf->Cell(45,7,"Name, signature and telephone*",1);
	$pdf->Cell(30,7,"");
	$pdf->Cell(45,7,"Name, signature and telephone*",1);
	$pdf->Cell(30,7,"");
	$pdf->Cell(45,7,"Name, signature and telephone*",1);
	$pdf->Cell(30,7,"");
	$pdf->Ln(19);
	$pdf->SetFont('Arial','B',10);
	$pdf->Cell(20,7,"*Request: ");
	$pdf->SetFont('Arial','u',10);
	$pdf->Cell(20,7,"                                          ");
	$pdf->Cell(60,7,"");
	$pdf->SetFont('Arial','B',10);
	$pdf->Cell(20,7,"*Ext: ");
	$pdf->SetFont('Arial','u',10);
	$pdf->Cell(20,7,"                                           ");
	$pdf->SetFont('Arial','i',7);
	$pdf->Ln(9);
	$pdf->Cell(20,7,"*INDISPENSABLE INFORMATION");
	$pdf->Output();
?>